---
- name: Install fastd package
  apt: name=fastd

- name: Create fastd ffmd configuration directory
  file: path=/etc/fastd/ffmd state=directory mode=0755

- name: Create fastd configuration
  template: src=fastd.conf dest=/etc/fastd/ffmd/fastd.conf mode=0644
