---
- name: Add fastd repository key
  apt_key: keyserver=pool.sks-keyservers.net id=6664E7BDA6B669881EC52E7516EF3F64CB201D9C

- name: Add fastd repository
  apt_repository: repo='deb http://repo.universe-factory.net/debian sid main'

- name: Install fastd package
  apt: name=fastd

- name: Create fastd ffmd configuration directory
  file: path=/etc/fastd/ffmd state=directory mode=0755

- name: Create fastd configuration
  template: src=fastd.conf dest=/etc/fastd/ffmd/fastd.conf mode=0644
