---
- name: Install batman-adv packages
  apt: name={{ item }} state=present
  with_items:
    - linux-headers-amd64
    - batman-adv-dkms
    - batctl

- name: Get version of loaded batman-adv kernel module
  command: batctl -v
  register: batman_adv_version
  changed_when: False

- name: Remove batman-adv dkms kernel module
  command: dkms remove batman-adv/2013.4.0 --all
  when: "batman_adv_version.stdout.find('batman-adv: 2013.4.0') == -1"

- name: Enable batman-adv dkms kernel module
  command: dkms --force install batman-adv/2013.4.0
  when: "batman_adv_version.stdout.find('batman-adv: 2013.4.0') == -1"

- name: Unload batman-adv kernel module
  command: modprobe -r batman-adv
  when: "batman_adv_version.stdout.find('batman-adv: 2013.4.0') == -1"

- name: Load batman-adv kernel module
  modprobe: name=batman-adv

- name: Check if batman-adv is loaded at boot
  lineinfile: dest=/etc/modules line=batman-adv
